#!/bin/sh
echo "[STAGING] merging & deploying to McMaster HSE"
git checkout develop
git merge master
git push staging develop:master

echo "deploying to McMaster HSE"
git push production master

echo "merging & deploying to PHCPI"
git checkout phcpi
git merge master
git push phcpi phcpi:master

echo "returning you back to master"
git checkout master
